### ISSUE TITLE
toggle is not persistent state 

### ISSUE THREAD

**Issue by bradholmes-studio** [ditdot-dev/dark-mode-example#4]
if toggled and the page changed the state resets to system preferences is it possible to add localStorage to this

**Comment by EkaterinaVu** [comment]
Hi @bradholmes-studio,

yes, it is possible. Here is a link to our article [Dark Mode - The prefers-color-scheme Website Tutorial](https://www.ditdot.hr/en/dark-mode-website-tutorial) and adding localStorage is described in the "How to Make Persistent User Choice Mode with JavaScript using localStorage" chapter.
